repos:
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1  
    hooks:
    -   id: black
        args: ["-l", "120"]
-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0 
    hooks:
    -   id: flake8
        args: ["--max-line-length=120"]